databases:
  - name: cse-dept-db
    databaseName: cse_dept_database
    user: cse_admin
    plan: free

services:
  - type: web
    name: cse-dept-website
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm ci
      npx prisma generate
      npx prisma db push
      npx prisma db seed
      npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cse-dept-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://cse-dept-website.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_NAME
        value: CSE Department - GIET
      - key: NEXT_PUBLIC_MAX_FILE_SIZE
        value: "10485760"
      - key: NEXT_PUBLIC_ALLOWED_FILE_TYPES
        value: "application/pdf,image/jpeg,image/png"
    autoDeploy: true
    buildFilter:
      paths:
      - app/**
      - components/**
      - lib/**
      - prisma/**
      - utils/**
      - hooks/**
      - middleware.ts
      - package.json
      - next.config.js
      - tsconfig.json
      - tailwind.config.js
      - postcss.config.js
      ignoredPaths:
      - README.md
      - .gitignore
      - .env*
      - public/uploads/**